In [158]:
import pandas as pd

In [159]:
df = pd.read_csv("C:\\Users\\bagchi\\Favorites\\Downloads\\datasets\\tmdb_5000_credits.csv")

In [160]:
df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [161]:
df['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

# As is clear from above, this dataset contains the cast details inside the "cast" column alongwith many other details that are not very useful for analysis. Also, the cast column is an object-type column that contains values in the form of dictionary but inside list, hence extracting only the artists' name is bit challenging. This work is done below for 2 movies (same code can be automated for al the movies)

In [162]:
df[df['title'] == 'Titanic']

,movie_id,title,cast,crew
25,597,Titanic,"[{""cast_id"": 20, ""character"": ""Rose DeWitt Buk...","[{""credit_id"": ""52fe425ac3a36847f8017985"", ""de..."

In [163]:
import re
test_str = df['cast'][25]

start = df['cast'][25].find('name')    
end = df['cast'][25].find('order') 
target_column = df['cast'][1][start:end]

test_sub = target_column


res = [i.start() for i in re.finditer("name", test_str)]
final = [0]*len(res)
for i in range(len(res)):
    final[i] = df['cast'][25][res[i]:res[i]+25]
final

['name": "Kate Winslet", "o',
 'name": "Leonardo DiCaprio',
 'name": "Frances Fisher", ',
 'name": "Billy Zane", "ord',
 'name": "Kathy Bates", "or',
 'name": "Gloria Stuart", "',
 'name": "Bill Paxton", "or',
 'name": "Bernard Hill", "o',
 'name": "David Warner", "o',
 'name": "Victor Garber", "',
 'name": "Jonathan Hyde", "',
 'name": "Suzy Amis", "orde',
 'name": "Lewis Abernathy",',
 'name": "Nicholas Cascone"',
 'name": "Danny Nucci", "or',
 'name": "Jason Barry", "or',
 'name": "Lew Palter", "ord',
 'name": "Eric Braeden", "o',
 'name": "Bernard Fox", "or',
 'name": "Ewan Stewart", "o',
 'name": "Ioan Gruffudd", "',
 'name": "Jonny Phillips", ',
 'name": "Edward Fletcher",',
 'name": "Scott G. Anderson',
 'name": "Martin East", "or',
 'name": "Gregory Cooke", "',
 'name": "Alexandrea Owens"',
 'name": "Seth Adkins", "or',
 'name": "Michael Ensign", ',
 'name": "Anatoly M. Sagale',
 'name": "Martin Hub", "ord',
 'name": "Mark Lindsay Chap',
 'name": "Richard Graham", ',
 'name": "Paul Brightwell",',
 'name": "Ron Donachie", "o',
 'name": "Charlotte Chatton',
 'name": "Fannie Brett", "o',
 'name": "Jenette Goldstein',
 'name": "Camilla Overbye R',
 'name": "Linda Kerns", "or',
 'name": "Amy Gaipa", "orde',
 'name": "Martin Jarvis", "',
 'name": "Rosalind Ayres", ',
 'name": "Rochelle Rose", "',
 'name": "Jonathan Evans-Jo',
 'name": "Brian Walsh", "or',
 'name": "Rocky Taylor", "o',
 'name": "Craig Kelly", "or',
 'name": "Liam Tuohy", "ord',
 'name": "Simon Crane", "or',
 'name": "James Lancaster",',
 'name": "Elsa Raven", "ord',
 'name": "Reece P. Thompson',
 'name": "Laramie Landis", ',
 'name": "Mark Rafael Truit',
 'name": "John Walcutt", "o',
 'name": "Terry Forrestal",',
 'name": "Derek Lea", "orde',
 'name": "Richard Ashton", ',
 'name": "Sean Nepita", "or',
 'name": "Brendan Connolly"',
 'name": "David Cronnelly",',
 'name": "Garth Wilton", "o',
 'name": "Richard Fox", "or',
 'name": "Nick Meaney", "or',
 'name": "Kevin Owers", "or',
 'name": "Mark Capri", "ord',
 'name": "Marc Cass", "orde',
 'name": "Paul Herbert", "o',
 'name": "Emmett James", "o',
 'name": "Chris Byrne", "or',
 'name": "Oliver Page", "or',
 'name": "James Garrett", "',
 'name": "Erik Holland", "o',
 'name": "Erik Holland", "o',
 'name": "Jari Kinnunen", "',
 'name": "Anders Falk", "or',
 'name": "Barry Dennen", "o',
 'name": "Vern Urich", "ord',
 'name": "Rebecca Klingler"',
 'name": "Tricia O\'Neil", "',
 'name": "Kathleen S. Dunn"',
 'name": "Romeo Francis", "',
 'name": "Mandana Marino", ',
 'name": "Van Ling", "order',
 'name": "Bj\\u00f8rn Olsen"',
 'name": "Dan Pettersson", ',
 'name": "Shay Duffin", "or',
 'name": "Greg Ellis", "ord',
 'name": "Diana Morgan", "o',
 'name": "Kris Andersson", ',
 'name": "Bobbie Bates", "o',
 'name": "Aaron James Cash"',
 'name": "Anne Fletcher", "',
 'name": "Edmond Alan Forsy',
 'name": "Andie Hicks", "or',
 'name": "Scott Hislop", "o',
 'name": "Stan Mazin", "ord',
 'name": "Lisa Ratzin", "or',
 'name": "Julene Renee", "o',
 'name": "Brian Baines", "o',
 'name": "Ellie Bensinger",',
 'name": "Alexandra Boyd", ',
 'name": "Mike Butters", "o',
 'name": "James Cameron", "',
 'name": "Bruno Campolo", "',
 'name": "Chris Cragnotti",',
 'name": "Kevyn Currie", "o',
 'name": "Kevin De La Noy",',
 'name": "Thomas Fiss", "or',
 'name": "Griffin Howell", ',
 'name": "Sean Howse", "ord',
 'name": "Tony Kenny", "ord',
 'name": "Bret Aaron Knower',
 'name": "George Kosty III"',
 'name": "George Kosty Jr."',
 'name": "Geoffrey C. Kosty',
 'name": "Gregory Charles K',
 'name": "Sean Lawlor", "or',
 'name": "John Leonhardt", ',
 'name": "Miguel A. Lomelin',
 'name": "Don Lynch", "orde',
 'name": "Johnny Martin", "',
 'name": "Ryan McClurkin", ',
 'name": "Meghan McLeod", "',
 'name": "Mike O\'Neal", "or',
 'name": "Julian Oros", "or',
 'name": "Phil Parlapiano",',
 'name": "Judy Prestininzi"',
 'name": "Steven Quale", "o',
 'name": "Olivia Rosewood",',
 'name": "John Slade", "ord',
 'name": "Stephen Wolfe Smi',
 'name": "R. Gern Trowbridg',
 'name": "Francisco V\\u00e1',
 'name": "Lucie Zolcerova",']

In [164]:
df[df['title'] == 'The Shawshank Redemption']

,movie_id,title,cast,crew
1881,278,The Shawshank Redemption,"[{""cast_id"": 3, ""character"": ""Andy Dufresne"", ...","[{""credit_id"": ""52fe4231c3a36847f800b153"", ""de..."

In [165]:
import re
test_str = df['cast'][1881]

start = df['cast'][1881].find('name')    
end = df['cast'][1881].find('order') 
target_column = df['cast'][1][start:end]

test_sub = target_column


res = [i.start() for i in re.finditer("name", test_str)]
final = [0]*len(res)
for i in range(len(res)):
    final[i] = df['cast'][1881][res[i]:res[i]+25]
final

['name": "Tim Robbins", "or',
 'name": "Morgan Freeman", ',
 'name": "Bob Gunton", "ord',
 'name": "Clancy Brown", "o',
 'name": "Mark Rolston", "o',
 'name": "James Whitmore", ',
 'name": "Gil Bellows", "or',
 'name": "William Sadler", ',
 'name": "Jeffrey DeMunn", ',
 'name": "Larry Brandenburg',
 'name": "Neil Giuntoli", "',
 'name": "Brian Libby", "or',
 'name": "David Proval", "o',
 'name": "Joseph Ragno", "o',
 'name": "Jude Ciccolella",',
 'name": "Paul McCrane", "o',
 'name": "Renee Blaine", "o',
 'name": "Scott Mann", "ord',
 'name": "John Horton", "or',
 'name": "Gordon Greene", "',
 'name": "Alfonso Freeman",',
 'name": "V.J. Foster", "or',
 'name": "Frank Medrano", "',
 'name": "Mack Miles", "ord',
 'name": "Gary Lee Davis", ',
 'name": "Ned Bellamy", "or',
 'name": "Brian Delate", "o',
 'name": "Don McManus", "or',
 'name": "Dorothy Silver", ',
 'name": "Dion Anderson", "',
 'name": "Robert Haley", "o',
 'name": "Bill Bolender", "',
 'name": "John R. Woodward"',
 'name": "Rohn Thomas", "or',
 'name": "Brian Brophy", "o',
 'name": "Ken Magee", "orde',
 'name": "James Babson", "o',
 'name": "Fred Culbertson",',
 'name": "Alonzo F. Jones",',
 'name": "Actor Sergio Kato',
 'name": "Philip Ettington"',
 'name": "Neil Summers", "o']